version: "3.1"
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: 1q2w3e4r5y
    server:
        image: yossik/nodeserver:twitter_dev_node_server
        restart: always
        ports: 
            - 80:3000
        environment:
            DB_PATH: postgres://postgres:1q2w3e4r5y@db:5432/postgres