version: "3.1"
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USERNAME: postgres
            POSTGRES_PASSWORD: 1q2w3e4r5y
            POSTGRES_DATABASE: postgres
    server:
        image: yossik/nodeserver:twitter_dev_node_server
        restart: always
        ports: 
            - 80:3000
        environment:
            DB_PATH: postgres://postgres:1q2w3e4r5y@db:5432/postgres
        depends_on: 
            - db
        command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'